export enum WebsocketEvent {
  MONAD_CHUNK_EVENT = 'MONAD_CHUNK',
  BPF_TRACE = 'BPF_TRACE',
  SYSTEM_LOG = 'SYSTEM_LOG',
  OFF_CPU = 'OFF_CPU',
  SCHEDULER = 'SCHEDULER',
  PERF_STAT = 'PERF_STAT',
  TURBO_STAT = 'TURBO_STAT',
  CLIENT_EVENT = 'CLIENT',
}

export enum NetworkEvent {
  MONAD_CHUNK,
  OUTBOUND_ROUTER,
}
