export enum WebsocketEvent {
  MONAD_CHUNK = 'MONAD_CHUNK',
  OUTBOUND_ROUTER = 'OUTBOUND_ROUTER',
  PING = 'PING',
  BPF_TRACE = 'BPF_TRACE',
  SYSTEM_LOG = 'SYSTEM_LOG',
  OFF_CPU = 'OFF_CPU',
  SCHEDULER = 'SCHEDULER',
  PERF_STAT = 'PERF_STAT',
  TURBO_STAT = 'TURBO_STAT',
}

export enum NetworkEvent {
  MONAD_CHUNK,
  OUTBOUND_ROUTER,
  PING_LATENCY,
}
