export enum WebsocketEvent {
  MONAD_CHUNK_EVENT = 'MONAD_CHUNK',
  JOURNAL_CTL_EVENT = 'JOURNAL_CTL',
  OFF_CPU_TIME_EVENT = 'OFF_CPU_TIME',
  PERF_SCHED_EVENT = 'PERF_SCHED',
  PERF_STAT_EVENT = 'PERF_STAT',
  TURBO_STAT_EVENT = 'TURBO_STAT',
  CLIENT_EVENT = 'CLIENT',
}

export enum NetworkEvent {
  MONAD_CHUNK,
  OUTBOUND_ROUTER,
}
